### ISSUE TITLE
Fatal error: Unsupported operand types in:

### ISSUE THREAD

**Issue by vikingdker** [drupalrestaurant/restaurant#15]
Trying to install Drupal restaurant 7.35 in standard mode gets:
Fatal error: Unsupported operand types in /data/home/smartweb/public_html/includes/install.core.inc on line 618
Any ideas to fix this.

Installing on quick mode works fine, but even i remove the demo content i admin/modules, content
still on page.

Ty.

**Comment by arshad** [comment]
Thanks. Looking into it.

**Comment by arshad** [comment]
This should be fixed now. You can test it on Pantheon or download the dev version here: http://ftp.drupal.org/files/projects/restaurant-7.x-1.x-dev-core.tar.gz

**Comment by vikingdker** [comment]
Hello you work fast i apriciate your job, is it possible to get zip file instead.
ty.

**Comment by arshad** [comment]
Sure. Here you go: http://ftp.drupal.org/files/projects/restaurant-7.x-1.x-dev-core.zip

**Comment by vikingdker** [comment]
Hello again, ty for sending new dev all install now works very good but drupal admin menu is not working anymore:
Using any menu give this error.
Ty.

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@smartwebsale.dk to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by vikingdker** [comment]
Ok i looked all files throw somehow the htaccess was not uploaded on my server, everything look fine thanks alot
i really apriciate your work

**Comment by arshad** [comment]
No worries. Thanks for the report. Helped us fix a bug.
