### ISSUE TITLE
Makefile error.

### ISSUE THREAD

**Issue by Polzme** [drupalrestaurant/restaurant#5]
The revision 'b52ea5d' doesn't exist for the contrib radix_core.

More info see: https://www.drupal.org/node/2457725

**Comment by arshad** [comment]
Thanks. Looking into this

**Comment by Polzme** [comment]
Any update on this ?

**Comment by arshad** [comment]
I looked at the d.o issue and thought this was fixed. Sorry.

It seems d.o is having issue building the make file as well.

Fixing...

**Comment by arshad** [comment]
Looks like d.o remote for radix_core was not updated. Just pushed. http://cgit.drupalcode.org/radix_core/commit/?id=b52ea5d

**Comment by Polzme** [comment]
Thanks, now it's building perfectly !
